//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wedding.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog
    {
        public int id { get; set; }
        public System.DateTime posted { get; set; }
        public bool deleted { get; set; }
        public Nullable<decimal> maplat { get; set; }
        public Nullable<decimal> maplon { get; set; }
        public Nullable<int> mapzoom { get; set; }
        public string title { get; set; }
        public string post { get; set; }
    }
}
