//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wedding.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_booking
    {
        public int id { get; set; }
        public Nullable<int> guest_id { get; set; }
        public Nullable<int> car_id { get; set; }
        public Nullable<int> route { get; set; }
        public Nullable<System.DateTime> added { get; set; }
    
        public virtual car car { get; set; }
        public virtual guest guest { get; set; }
    }
}
