//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wedding.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class food
    {
        public int id { get; set; }
        public Nullable<int> guest_id { get; set; }
        public string food_comment { get; set; }
        public Nullable<bool> lactose { get; set; }
        public Nullable<bool> vegan { get; set; }
        public Nullable<bool> vegetarian { get; set; }
        public Nullable<bool> pescetarian { get; set; }
        public Nullable<System.DateTime> added { get; set; }
        public Nullable<bool> gluten { get; set; }
        public Nullable<bool> nut { get; set; }
        public Nullable<bool> bringscake { get; set; }
        public Nullable<bool> nonalco { get; set; }
    
        public virtual guest guest { get; set; }
    }
}
